name: Pipepilen Back Challenge

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create database
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE \"pipelines_db\";"

      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/pipelines_db
          
        run: |
          source venv/bin/activate
          python manage.py migrate
      
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: system.settings
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          source venv/bin/activate
          coverage run manage.py test