name: Pipepilen Back Challenge

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Inicia o setup do python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.8'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepara o banco de dados
        run: |
          python manage.py migrate

      - name: Rodar testes
        run: |
          coverage run (link unavailable) test